name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app/
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set Default Scheme
        run: |
          TEMP_DIR=$(mktemp -d)
          cd $TEMP_DIR
          curl -sSLo flutter.zip https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_1.22.5-stable.zip
          unzip flutter.zip
          mv flutter ${HOME}/.local/share/flutter
          echo "${HOME}/.local/share/flutter/bin" >> $GITHUB_PATH
          flutter doctor
